name: martial_notes
description: Minimal Martial Arts Technique Note-Taking App
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # UI and platform
  provider: ^6.1.1
  path_provider: ^2.1.1
  path: ^1.8.3
  uuid: ^4.2.2

  # Rich text editor
  flutter_quill: ^11.0.0

  # Media picker
  image_picker: ^1.0.4
  camera: ^0.11.3

  # Database (Drift)
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  drift_dev: ^2.14.1

flutter:
  uses-material-design: true
